export default class BreakpointConstants{
  static readonly BREAKPOINT_SM: string = 'SM'
  static readonly BREAKPOINT_MD: string = 'md'
  static readonly BREAKPOINT_LG: string = 'lg'
  static readonly CURRENT_BREAKPOINT: string = 'currentBreakpoint'
  static readonly RANGE_SM: string = '(320vp<=width<600vp)'
  static readonly RANGE_MD: string = '(600vp<=width<840vp)'
  static readonly RANGE_LG: string = '(840vp<=width)'
}